# Generated by Django 6.0.1 on 2026-01-25 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_student_alter_post_options_rename_content_post_body_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
