# Generated by Django 6.0.1 on 2026-01-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='title',
        ),
    ]
