# Generated by Django 5.2.10 on 2026-01-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_employee_id_alter_post_id_alter_student_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
